language: php
#
#branches:
#    only: master

matrix:
  fast_finish: true
  include:
    - php: 7.2

install:
    - phpenv config-rm xdebug.ini || echo 'xdebug not available'
    - phpenv config-add docker/php/config/php.ini
    - composer install --classmap-authoritative

script:
    - bin/benchmark --vertical-complexity 1   --horizontal-complexity 60  --iteration 3
    - bin/benchmark --vertical-complexity 60  --horizontal-complexity 1   --iteration 3
    - bin/benchmark --vertical-complexity 60  --horizontal-complexity 60  --iteration 3

