language: php

php:
    - 5.6
    - 7.0

branches:
    only: master

install:
    - if [[ $TRAVIS_PHP_VERSION = 5.6 ]]; then printf "\n" | pecl install apcu-4.0.10; fi
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then printf "\n" | pecl install apcu; fi
    - phpenv config-rm xdebug.ini
    - phpenv config-add etc/www.ini
    - composer self-update
    - composer install --prefer-source --optimize-autoloader

script:
    - bin/benchmark --iteration 100
    - bin/benchmark --horizontal-complexity 4 --iteration 100
    - bin/benchmark --vertical-complexity 4 --iteration 100
    - bin/benchmark --horizontal-complexity 4 --vertical-complexity 4 --iteration 100
