language: php
#
#branches:
#    only: master

matrix:
  fast_finish: true
  include:
    - php: 7.2

install:
  - phpenv config-rm xdebug.ini || echo 'xdebug not available'
  - phpenv config-add docker/php/config/php.ini
  - composer install --classmap-authoritative

script:
  - ./vendor/bin/phpbench run --report=aggregate-sorted --parameters='[1,60]' --progress=dots
  - ./vendor/bin/phpbench run --report=aggregate-sorted --parameters='[60,1]' --progress=dots
  - ./vendor/bin/phpbench run --report=aggregate-sorted --parameters='[60,60]' --progress=dots

