version: '2'

services:
    php: &php
        build: docker/php
        env_file:
            - .env
        volumes:
            - ~/.composer:/var/www/.composer
            - .:/var/www/html
    hhvm:
        <<: *php
        build: docker/hhvm
