version: '2'

services:
    php:
        build: docker
        environment:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}
        volumes:
            - ~/.composer:/var/www/.composer
            - .:/var/www/html
